# Generated by Django 4.2.5 on 2023-09-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table='tblstaff',
        ),
    ]
